Add StatusText field
loadimpact/k6 pull request #1649
Opened 2020-10-04 12:29 UTC by lcd1232

Closes #1585

2020-10-04 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/loadimpact/k6?pullRequest=1649) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/loadimpact/k6?pullRequest=1649) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/loadimpact/k6?pullRequest=1649) it.</sub>

2020-10-04 13:02 UTC, lcd1232 commented
@MStoykov could you add the topic `hacktoberfest `? Right now PR has status as "Ineligible Repository"
![image](https://user-images.githubusercontent.com/8745863/95016304-e55f8d80-065a-11eb-88e7-36acbaea9b4a.png)

2020-10-05 10:38 UTC, MStoykov commented
@lcd1232 I added it :)

2020-10-05 11:33 UTC, imiric requested changes
Hi, thanks for your contribution. Would you mind adding unit tests for this change?

2020-10-11 10:18 UTC, lcd1232 commented
@imiric I fixed linter and add tests. Could you review, please?

2020-10-11 10:34 UTC, lcd1232 commented
@imiric and could you help with data race in tests? Not sure why it's happeninged

2020-10-12 08:13 UTC, MStoykov submitted a review, later dismissed

2020-10-12 08:32 UTC, na-- submitted a review, later dismissed

2020-10-12 09:59 UTC, imiric submitted a review, later dismissed
LGTM, thanks for the test!

2020-10-12 09:59 UTC, imiric commented on lib/netext/httpext/request_test.go
> +					//require.NoError(t, err)
Delete this?

2020-10-12 10:17 UTC, MStoykov approved these changes

2020-10-12 10:21 UTC, lcd1232 commented on lib/netext/httpext/request_test.go
> +					//require.NoError(t, err)
Done

2020-10-12 10:24 UTC, merged