Add/move SharedArray tests to it's module
loadimpact/k6 pull request #1795
Opened 2021-01-12 10:23 UTC by MStoykov

2021-01-12 10:24 UTC, MStoykov commented on js/modules/k6/data/share_test.go
> +	require.NoError(t, err)
Couldn't figure out what to name this block of code ... so I didn't move it to a function :shrug:

2021-01-12 11:22 UTC, imiric requested changes
Thanks, this cleans up that JS integration test nicely!

Just spotted a small typo I think.

2021-01-12 11:22 UTC, imiric commented on js/modules/k6/data/share_test.go
> +		throw new Error("bad length " +_array.length);
```suggestion
		throw new Error("bad length " +array.length);
```

2021-01-12 13:05 UTC, imiric approved these changes

2021-01-13 12:00 UTC, na-- approved these changes

2021-01-13 12:05 UTC, merged