[WIP] Move the cloud output to the new Output interface
loadimpact/k6 pull request #1874
Opened 2021-03-01 12:25 UTC by na--

Follow up to https://github.com/loadimpact/k6/pull/1869 and https://github.com/loadimpact/k6/pull/1870. 

The logic should be all be there, so from a functional standpoint this PR is ready. It's `WIP` because I want to clean up some stuff, for example rename `collector` and `c` in the actual code to `output` and `o`/`out`, as well as fix some minor linter issues that remain. I'll probably do that after https://github.com/loadimpact/k6/pull/1856 is merged and I rebase on top of it, so it should be fine for review of the logic now.

2021-03-02 16:31 UTC, MStoykov approved these changes
LGTM.

2021-03-02 16:31 UTC, MStoykov commented on cloudapi/util.go
> +	return fmt.Sprintf("%s/runs/%s", config.WebAppURL.String, refID)
nit ... maybe just concat them with `+` ...?

2021-03-02 16:37 UTC, MStoykov requested changes
actually just checked 2 or 3 things I wasn't sure about with the config and a thing that definitely doesn't work is picking up my subscription from the config file

2021-03-04 11:53 UTC, na-- commented on cloudapi/util.go
> +	return fmt.Sprintf("%s/runs/%s", config.WebAppURL.String, refID)
resolved by https://github.com/loadimpact/k6/compare/a67b3a127823480eff7038aa32f812d93ad5a2ac..7d50a9ea51f50006cad35a246b29ac1623ad8699

2021-03-04 12:06 UTC, MStoykov approved these changes

2021-03-04 12:49 UTC, na-- commented
This is now ready for merging from my side, I've renamed all `Collector` / `c` mentions to `Output` / `out`, and I've cleaned up some of the linter issues that were present. I suggest reading the changes commit by commit.

2021-03-04 14:22 UTC, MStoykov approved these changes

2021-03-04 14:44 UTC, merged