Removed fixes to enable TLS v1.3
loadimpact/k6 pull request #1902
Opened 2021-03-13 11:26 UTC by codebien

Removed the functions to enable TLS1.3 on Go 1.11 and 1.12

2021-03-15 08:25 UTC, na-- requested changes
Thanks! Please also completely remove the `TLSVersion13` constant everywhere in the k6 code and use the Go stdlib's `tls.VersionTLS13` one. For example here: https://github.com/loadimpact/k6/blob/253ad5406a85d222b1d30fb563ef63b32cc7e9a3/lib/tlsconfig.go#L28-L33

2021-03-17 07:51 UTC, na-- commented on lib/options.go
>  func (v *TLSVersions) isTLS13() bool {
I think we can safely delete this whole method now.

2021-03-17 07:54 UTC, na-- submitted a review, later dismissed
Thanks, LGTM besides the minor nitpick I noted as an inline comment.

2021-03-17 19:29 UTC, codebien commented
Done, method removed

2021-03-18 08:04 UTC, na-- approved these changes

2021-03-18 08:17 UTC, MStoykov approved these changes

2021-03-18 09:11 UTC, merged